version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres_local
    restart: always
    environment:
      POSTGRES_USER: lucas
      POSTGRES_PASSWORD: minha_senha_segura
      POSTGRES_DB: meu_banco
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
